### ISSUE TITLE
cannot list more items >12 item in 3d bar graphs

### ISSUE THREAD

**Issue by sailendraw** [lecterror/cakephp-fusion-charts-plugin#4]
Hi there 
i was trying to list the item using 3d bar but it only shows me 12 items rest of item disappeared, and name of the material are overlapping,,why there are 12 bar when there is more item left,it is just because 12 color is available.?

**Comment by lecterror** [comment]
Hmm..there is nothing in the plugin which could limit this, have you tried creating a chart without the plugin? Maybe it's a limitation of the library..or the size of the chart you're creating?

**Comment by sailendraw** [comment]
Problem solved,,it was mainly because if value is 0 then it wont display chart,,Thank you for your kind co-operation and value-able time
